name: AI Code Review (Working)

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  ai-code-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    
    # Skip review for dependabot PRs
    if: github.actor != 'dependabot[bot]'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: "latest"

      - name: Configure Poetry
        run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local

      - name: Install Dependencies
        run: |
          poetry install

      - name: Test Environment
        run: |
          echo "Testing environment..."
          poetry run streetrace --version || echo "StreetRace not available"
          which gh || echo "GitHub CLI not available"

      - name: Post Basic Comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Posting basic AI review comment..."
          
          COMMENT="🤖 **AI Code Review (Working Version)**

**Pull Request Details:**
- **Number**: #${{ github.event.pull_request.number }}
- **Title**: ${{ github.event.pull_request.title }}
- **Author**: @${{ github.event.pull_request.user.login }}
- **Branch**: \`${{ github.event.pull_request.base.ref }}\` ← \`${{ github.event.pull_request.head.ref }}\`

**Status**: ✅ Basic workflow is functioning correctly!

This is a simplified version of the AI code review workflow. The full implementation with AI analysis will be enabled once all components are validated.

---
*Generated by StreetRace GitHub Actions Workflow*"

          gh pr comment ${{ github.event.pull_request.number }} --body "$COMMENT"