name: AI Code Review

on:
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.github/**'
      - 'LICENSE'
      - '.gitignore'

jobs:
  ai-code-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    
    # Skip review for dependabot PRs to avoid unnecessary API usage
    if: github.actor != 'dependabot[bot]'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: "latest"

      - name: Configure Poetry
        run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local

      - name: Install StreetRace
        run: |
          poetry lock
          poetry install

      - name: Validate Configuration
        run: |
          ./scripts/validate-config.sh

      - name: Extract PR Changes
        id: extract-diff
        run: |
          ./scripts/github-diff-extractor.sh > /tmp/pr-diff.txt
          echo "diff-size=$(wc -c < /tmp/pr-diff.txt)" >> $GITHUB_OUTPUT

      - name: Check diff size
        id: check-size
        run: |
          DIFF_SIZE=${{ steps.extract-diff.outputs.diff-size }}
          if [ "$DIFF_SIZE" -gt 100000 ]; then
            echo "Diff too large ($DIFF_SIZE bytes). Skipping AI review to avoid excessive token usage."
            echo "large-diff=true" >> $GITHUB_OUTPUT
            exit 0
          fi
          echo "large-diff=false" >> $GITHUB_OUTPUT

      - name: Run AI Code Review
        if: steps.check-size.outputs.large-diff != 'true'
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GOOGLE_AI_API_KEY: ${{ secrets.GOOGLE_AI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
          BASE_BRANCH: ${{ github.event.pull_request.base.ref }}
          HEAD_BRANCH: ${{ github.event.pull_request.head.ref }}
        run: |
          # Determine which AI model to use based on available API keys
          if [ -n "$ANTHROPIC_API_KEY" ]; then
            MODEL="anthropic/claude-3-5-sonnet-20241022"
          elif [ -n "$OPENAI_API_KEY" ]; then
            MODEL="openai/gpt-4o-mini"
          elif [ -n "$GOOGLE_AI_API_KEY" ]; then
            MODEL="google/gemini-1.5-flash"
          else
            echo "No API key configured. Please set ANTHROPIC_API_KEY, OPENAI_API_KEY, or GOOGLE_AI_API_KEY."
            exit 1
          fi
          
          echo "Using AI model: $MODEL"
          
          # Prepare the review context
          DIFF_CONTENT=$(cat /tmp/pr-diff.txt)
          
          # Create review prompt with embedded variables using Python
          python3 -c "
import os
with open('templates/github-review-prompt.md', 'r') as f:
    template = f.read()

with open('/tmp/pr-diff.txt', 'r') as f:
    pr_diff = f.read()

# Substitute variables
template = template.replace('\${PR_NUMBER}', os.environ.get('PR_NUMBER', ''))
template = template.replace('\${PR_TITLE}', os.environ.get('PR_TITLE', ''))
template = template.replace('\${PR_AUTHOR}', os.environ.get('PR_AUTHOR', ''))
template = template.replace('\${BASE_BRANCH}', os.environ.get('BASE_BRANCH', ''))
template = template.replace('\${HEAD_BRANCH}', os.environ.get('HEAD_BRANCH', ''))
template = template.replace('\${PR_DIFF}', pr_diff)

with open('/tmp/review-prompt.md', 'w') as f:
    f.write(template)
"
          
          # Run the AI review
          poetry run streetrace \
            --model="$MODEL" \
            --prompt="$(cat /tmp/review-prompt.md)" \
            > /tmp/review-output.txt 2>&1
          
          # Extract clean AI response
          if grep -q "StreetRace:" /tmp/review-output.txt; then
            sed -n '/StreetRace:/,/^$/p' /tmp/review-output.txt | sed '1d' > /tmp/clean-review.txt
          else
            cp /tmp/review-output.txt /tmp/clean-review.txt
          fi

      - name: Post Review Comment
        if: steps.check-size.outputs.large-diff != 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          ./scripts/post-review-comment.sh /tmp/clean-review.txt

      - name: Post Large Diff Notice
        if: steps.check-size.outputs.large-diff == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          COMMENT="🤖 **AI Code Review Skipped**

This PR contains a large diff (${{ steps.extract-diff.outputs.diff-size }} bytes) that would exceed reasonable token limits for AI review.

Consider:
- Breaking this PR into smaller, focused changes
- Running local code review using \`./scripts/code-review-poc.sh\`
- Focusing the review on specific files or components

You can still run manual review with:
\`\`\`bash
git checkout ${{ github.event.pull_request.head.ref }}
./scripts/code-review-poc.sh
\`\`\`"

          gh pr comment $PR_NUMBER --body "$COMMENT"

      - name: Archive review results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: code-review-results
          path: /tmp/*review*.txt
          retention-days: 30