name: StreetRace Review

on:
  pull_request:
    types: [opened]

jobs:
  streetrace-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      security-events: write
    
    # Skip review for dependabot PRs
    if: github.actor != 'dependabot[bot]'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: "latest"

      - name: Configure Poetry
        run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local

      - name: Install StreetRace
        run: |
          poetry install

      - name: Run Code Review
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          STREETRACE_MODEL: "openai/gpt-4o"
        run: |
          # Run the StreetRace review system
          python3 ./.github/workflows/scripts/code-review.py

      - name: Post Code Review Comment
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            
            // Read the markdown review file
            const reviewFile = 'code-review-result.md';
            let reviewContent = '';
            
            try {
              reviewContent = fs.readFileSync(reviewFile, 'utf8');
            } catch (error) {
              console.log('No review file found, posting error message');
              reviewContent = '# Code Review Failed\n\nThe code review could not be completed. Please check the workflow logs for more details.';
            }
            
            // Prepare the comment body
            const commentBody = `## 🔍 StreetRace Code Review\n\n${reviewContent}\n\n---\n*Review generated by [StreetRace](https://github.com/krmrn42/street-race) AI*`;
            
            // Find existing comment
            const comments = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });
            
            const existingComment = comments.data.find(comment => 
              comment.body.includes('🔍 StreetRace Code Review')
            );
            
            if (existingComment) {
              // Update existing comment
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: existingComment.id,
                body: commentBody
              });
              console.log('Updated existing code review comment');
            } else {
              // Create new comment
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: commentBody
              });
              console.log('Created new code review comment');
            }
