name: Profile Startup on PR

on:
  pull_request:
    paths:
      - 'scripts/profile_startup.py'
      - 'scripts/compare_profiles.py'
      - 'src/**'
      - 'pyproject.toml'
      - 'poetry.lock'

jobs:
  profile_startup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4

      - name: Check if scripts exist in PR branch
        id: scripts_in_pr
        run: |
          exists_startup="false"
          exists_compare="false"
          if [ -f scripts/profile_startup.py ]; then
            exists_startup="true"
          fi
          if [ -f scripts/compare_profiles.py ]; then
            exists_compare="true"
          fi
          echo "startup=${exists_startup}" >> $GITHUB_OUTPUT
          echo "compare=${exists_compare}" >> $GITHUB_OUTPUT

      - name: Set up Python
        if: steps.scripts_in_pr.outputs.startup == 'true'
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        if: steps.scripts_in_pr.outputs.startup == 'true'
        run: pip install poetry

      - name: Install dependencies
        if: steps.scripts_in_pr.outputs.startup == 'true'
        run: poetry install

      - name: Run profile on PR branch
        if: steps.scripts_in_pr.outputs.startup == 'true'
        run: poetry run python scripts/profile_startup.py --json --save=profile_pr.json

      - name: Save PR branch commit SHA
        if: steps.scripts_in_pr.outputs.startup == 'true'
        id: pr_sha
        run: echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Fetch and checkout main branch
        if: steps.scripts_in_pr.outputs.startup == 'true'
        run: git fetch origin main:main && git checkout main

      - name: Check if scripts exist in main branch
        id: scripts_in_main
        if: steps.scripts_in_pr.outputs.startup == 'true'
        run: |
          exists_startup="false"
          exists_compare="false"
          if [ -f scripts/profile_startup.py ]; then
            exists_startup="true"
          fi
          if [ -f scripts/compare_profiles.py ]; then
            exists_compare="true"
          fi
          echo "startup=${exists_startup}" >> $GITHUB_OUTPUT
          echo "compare=${exists_compare}" >> $GITHUB_OUTPUT

      - name: Install dependencies for main
        if: steps.scripts_in_main.outputs.startup == 'true'
        run: poetry install

      - name: Run profile on main branch
        if: steps.scripts_in_main.outputs.startup == 'true'
        run: poetry run python scripts/profile_startup.py --json --save=profile_main.json

      - name: Compare results
        if: steps.scripts_in_main.outputs.compare == 'true'
        run: python scripts/compare_profiles.py profile_main.json profile_pr.json diff_report.md

      - name: Restore PR branch for reporting
        if: steps.scripts_in_pr.outputs.startup == 'true'
        run: git checkout ${{ steps.pr_sha.outputs.sha }}

      - name: Comment PR-only results if main missing
        if: steps.scripts_in_pr.outputs.startup == 'true' && steps.scripts_in_main.outputs.startup != 'true'
        run: echo "# Startup Profile (PR only)\n" > diff_report.md && cat profile_pr.json >> diff_report.md

      - name: Comment on PR
        if: steps.scripts_in_pr.outputs.startup == 'true'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: diff_report.md

      - name: No profiling; skip job
        if: steps.scripts_in_pr.outputs.startup != 'true'
        run: echo "scripts/profile_startup.py not present on PR branch, skipping profiling step."
