# .github/workflows/quality-checks.yml

name: Python Code Quality Checks

on:
  push:
    branches: [ main ] # Adjust branches as needed
  pull_request:
    branches: [ main ] # Adjust branches as needed

jobs:
  quality-checks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' # Or your target Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run isort (check only)
      run: isort --check-only --diff src tests

    - name: Run black (check only)
      run: black --check --diff src tests

    - name: Run flake8
      run: flake8 src tests

    - name: Run mypy
      run: mypy src tests

    - name: Run pytest
      run: pytest
