name: Release

on:
  push:
    tags:
      - "v*" # Matches tags like v1.2.3

jobs:
  release:
    name: Publish PyPI Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: pip install poetry

      - name: Build
        run: poetry build

      - name: Publish to PyPI
        env:
          POETRY_PYPI_TOKEN: ${{ secrets.POETRY_PYPI_TOKEN }}
        run: poetry publish --username __token__ --password "$POETRY_PYPI_TOKEN"
